#!/usr/bin/env python
import subprocess
from os import path
import sys

core_path = path.dirname(path.dirname(path.dirname(path.abspath(__file__))))
site_path = path.abspath('%s/sites/default' % core_path)
print core_path
print site_path
subprocess.call(['rm', '-Rf', '%s/files/' % site_path, '%s/settings.php' % site_path])
subprocess.call(['rm', '-Rf', '%s/profiles/shelepen/config/install/' % core_path])
subprocess.call(['mkdir', '%s/files' % site_path])
subprocess.call(['cp', '-R', '%s/core/profiles/standard/config/install/' % core_path, '%s/profiles/shelepen/config/' % core_path])
subprocess.call('cp %s/profiles/shelepen/config/changed/* %s/profiles/shelepen/config/install' % (core_path, core_path), shell=True)
subprocess.call(['cp', '%s/default.settings.php' % site_path, '%s/settings.php' % site_path])
subprocess.call(['chown', 'www-data:www-data', '%s/files/' % site_path, '%s/settings.php' % site_path])
subprocess.call('mysql -uroot --password="" --execute="DROP DATABASE d8; CREATE DATABASE d8;"', shell=True)
subprocess.call('/home/viktor/github/drush/drush --root=%s si -y shelepen --db-url="mysql://root:@localhost/d8" --site-name="Shelepen" --account-name="admin" --account-pass="admin"' % core_path, shell=True)
#subprocess.call(['/home/viktor/github/drush/drush', '--root=%s' % site_path, 'si'])
